on:
  workflow_dispatch:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]  # Note: macos-26 doesn't exist yet
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install LibUSB
      run: |
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        echo >> /Users/runner/.bash_profile
        echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> /Users/runner/.bash_profile
        eval "$(/opt/homebrew/bin/brew shellenv)"
        brew uninstall libusb --ignore-dependencies
        brew install libusb --head
        
    # Add your build steps here (gradle build, etc.)
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Mac-${{ matrix.os }}
        path: /opt/homebrew/Cellar/libusb/HEAD-18d26e4/lib/libusb-1.0.0.dylib
