name: Build LibUSB Manually

on:
  workflow_dispatch:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [macos-14, macos-15, macos-26]
    runs-on: ${{ matrix.os }}
  
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job
      # can access it
      - uses: actions/checkout@v3

      - name: setup prerequisites
        shell: bash
        run: |
          brew update
          brew install autoconf automake libtool m4

      - name: bootstrap
        shell: bash
        run: ./bootstrap.sh

      - name: compile
        shell: bash
        run: .private/ci-build.sh --build-dir build

      - name: Xcode
        shell: bash
        run: cd Xcode && xcodebuild -project libusb.xcodeproj
